"""Automated Citation Validator and Factuality Checker (Phase 9).

Validates that every factual statement generated by the LLM maps to verified
retrieved evidence, detects hallucinated citations ([E99]), checks factual
consistency using Scientific NLI and lexical overlap, and computes the
Evidence Support Rate.
"""

import re
from typing import Dict, List, Optional, Set, Tuple

from backend.app.core.logging import get_logger
from backend.app.models.paper import (
    CitationSource,
    CitationValidationReport,
    ClaimValidationItem,
    ClaimValidationStatus,
)
from backend.app.services.gaps.verification_service import NLILabel, ScientificNLIEngine

logger = get_logger("app.llm.citation_validator")

# Regex to capture citation tags like [E1], [E2], [E12]
CITATION_PATTERN = re.compile(r"\[(E\d+)\]", re.IGNORECASE)

# Sentence boundary regex for extracting claim statements
SENTENCE_SPLIT_PATTERN = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9])")


class CitationValidator:
    """Automated validator for citation references in generated LLM synthesis text."""

    def __init__(self, min_support_score: float = 0.50):
        self.min_support_score = min_support_score

    def extract_citations(self, text: str) -> List[str]:
        """Extract all citation IDs (e.g. ['E1', 'E2']) mentioned in the text."""
        raw_matches = CITATION_PATTERN.findall(text)
        # Normalize to uppercase E1, E2...
        return [m.upper() for m in raw_matches]

    def split_claims(self, text: str) -> List[str]:
        """Segment a paragraph or section into distinct claim statements."""
        if not text or not text.strip():
            return []
        lines = [line.strip() for line in text.split("\n") if line.strip()]
        claims = []
        for line in lines:
            # If line is bullet or numbered list
            clean_line = re.sub(r"^[\*\-\d\.\s]+", "", line).strip()
            if not clean_line:
                continue
            sentences = SENTENCE_SPLIT_PATTERN.split(clean_line)
            for s in sentences:
                s_clean = s.strip()
                if len(s_clean) > 10:  # Ignore trivial fragments
                    claims.append(s_clean)
        return claims

    def _compute_lexical_overlap(self, text1: str, text2: str) -> float:
        """Compute semantic token overlap (max of Jaccard and containment) between claim and source evidence."""
        stopwords = {
            "the", "a", "an", "is", "are", "was", "were", "and", "or", "in", "on", "at",
            "to", "for", "of", "with", "by", "that", "this", "these", "those", "it",
            "we", "our", "they", "their", "from", "as", "be", "been", "has", "have",
        }
        tokens1 = {w.lower() for w in re.findall(r"\b[a-zA-Z]{3,}\b", text1) if w.lower() not in stopwords}
        tokens2 = {w.lower() for w in re.findall(r"\b[a-zA-Z]{3,}\b", text2) if w.lower() not in stopwords}
        if not tokens1 or not tokens2:
            return 0.0
        intersection = tokens1.intersection(tokens2)
        union = tokens1.union(tokens2)
        jaccard = len(intersection) / len(union)
        containment = len(intersection) / min(len(tokens1), len(tokens2))
        return max(jaccard, containment)

    def validate_claim(
        self,
        claim: str,
        citations: Dict[str, CitationSource],
    ) -> ClaimValidationItem:
        """Validate whether the citations in a claim statement support the asserted content."""
        cited_tags = self.extract_citations(claim)

        # 1. No citations in this claim
        if not cited_tags:
            return ClaimValidationItem(
                claim_text=claim,
                cited_ids=[],
                status=ClaimValidationStatus.INSUFFICIENT_EVIDENCE,
                support_score=0.0,
                explanation="Statement does not contain explicit grounded evidence citations.",
                matching_sources=[],
            )

        # 2. Check for unknown / hallucinated citation tags
        hallucinated_tags = [tag for tag in cited_tags if tag not in citations]
        if hallucinated_tags:
            return ClaimValidationItem(
                claim_text=claim,
                cited_ids=cited_tags,
                status=ClaimValidationStatus.HALLUCINATED_CITATION,
                support_score=0.0,
                explanation=f"Hallucinated citation(s) detected: {', '.join(hallucinated_tags)}. Tags not in evidence context.",
                matching_sources=[],
            )

        # 3. Evaluate each cited source against the claim
        matching_sources = [citations[tag] for tag in cited_tags]
        best_support_score = 0.0
        best_explanation = ""
        is_contradicted = False

        # Clean claim text (strip bracket tags and any leading label prefix for comparison)
        clean_claim_text = CITATION_PATTERN.sub("", claim).strip()
        clean_claim_text = re.sub(r"^[a-zA-Z_]+:\s*", "", clean_claim_text).strip()

        for tag in cited_tags:
            source = citations[tag]
            src_text = source.sentence_text.strip()

            # Scientific NLI check: does premise (source_text) entail hypothesis (claim)?
            nli_eval = ScientificNLIEngine.evaluate(premise=src_text, hypothesis=clean_claim_text)
            overlap = self._compute_lexical_overlap(clean_claim_text, src_text)

            if nli_eval.label == NLILabel.CONTRADICTION:
                is_contradicted = True
                score = 0.0
                best_explanation = f"Cited evidence [{tag}] contradicts claim: source states '{src_text[:80]}...'"
                best_support_score = 0.0
                break

            elif nli_eval.label == NLILabel.ENTAILMENT:
                score = max(0.85, nli_eval.confidence)
                if score > best_support_score:
                    best_support_score = score
                    best_explanation = f"Entailed by [{tag}] ('{src_text[:60]}...') with confidence {score:.2f}."

            else:  # NEUTRAL
                # Check lexical/semantic overlap
                if overlap >= 0.25:
                    score = min(0.80, 0.40 + overlap)
                    if score > best_support_score:
                        best_support_score = score
                        best_explanation = f"Semantically consistent with [{tag}] (token overlap: {overlap:.2f})."
                else:
                    score = overlap
                    if score > best_support_score:
                        best_support_score = score
                        best_explanation = f"Weak alignment with [{tag}] (token overlap: {overlap:.2f} below threshold)."

        # Determine final status for this claim
        if is_contradicted:
            status = ClaimValidationStatus.CONTRADICTED
        elif best_support_score >= self.min_support_score:
            status = ClaimValidationStatus.SUPPORTED
        else:
            status = ClaimValidationStatus.UNSUPPORTED
            if not best_explanation:
                best_explanation = f"Cited evidence does not sufficiently support claim assertion (score: {best_support_score:.2f})."

        return ClaimValidationItem(
            claim_text=claim,
            cited_ids=cited_tags,
            status=status,
            support_score=round(best_support_score, 3),
            explanation=best_explanation,
            matching_sources=matching_sources,
        )

    def validate_text(
        self,
        text: str,
        citations: Dict[str, CitationSource],
        min_support_rate: float = 0.60,
    ) -> CitationValidationReport:
        """Validate all claims across a text block and generate a full audit report."""
        claims = self.split_claims(text)
        evaluated_items: List[ClaimValidationItem] = []

        total_claims = len(claims)
        claims_with_citations = 0
        supported_claims = 0
        unsupported_claims = 0
        contradicted_claims = 0
        hallucinated_citations = 0
        rejection_reasons: List[str] = []

        for claim in claims:
            res = self.validate_claim(claim, citations)
            evaluated_items.append(res)

            if res.cited_ids:
                claims_with_citations += 1

            if res.status == ClaimValidationStatus.SUPPORTED:
                supported_claims += 1
            elif res.status == ClaimValidationStatus.UNSUPPORTED:
                unsupported_claims += 1
            elif res.status == ClaimValidationStatus.CONTRADICTED:
                contradicted_claims += 1
                rejection_reasons.append(f"Contradicted claim: '{claim[:60]}...'")
            elif res.status == ClaimValidationStatus.HALLUCINATED_CITATION:
                hallucinated_citations += 1
                rejection_reasons.append(f"Hallucinated citation in claim: '{claim[:60]}...'")

        # Evidence Support Rate calculation
        if claims_with_citations > 0:
            evidence_support_rate = supported_claims / claims_with_citations
        else:
            evidence_support_rate = 0.0

        is_valid = (
            hallucinated_citations == 0
            and contradicted_claims == 0
            and evidence_support_rate >= min_support_rate
        )

        if evidence_support_rate < min_support_rate and claims_with_citations > 0:
            rejection_reasons.append(
                f"Evidence support rate {evidence_support_rate:.2%} is below threshold {min_support_rate:.2%}."
            )

        return CitationValidationReport(
            total_claims=total_claims,
            claims_with_citations=claims_with_citations,
            supported_claims=supported_claims,
            unsupported_claims=unsupported_claims,
            contradicted_claims=contradicted_claims,
            hallucinated_citations=hallucinated_citations,
            evidence_support_rate=round(evidence_support_rate, 3),
            is_valid=is_valid,
            rejection_reasons=rejection_reasons,
            claims=evaluated_items,
        )

    def validate_sections(
        self,
        sections: Dict[str, str],
        citations: Dict[str, CitationSource],
        min_support_rate: float = 0.60,
    ) -> CitationValidationReport:
        """Validate multiple synthesis sections and aggregate into a comprehensive report."""
        combined_text = "\n\n".join([sec_text.strip() for sec_text in sections.values() if sec_text and sec_text.strip()])
        return self.validate_text(combined_text, citations, min_support_rate=min_support_rate)


_global_citation_validator: Optional[CitationValidator] = None


def get_citation_validator(min_support_score: float = 0.50) -> CitationValidator:
    """Retrieve global CitationValidator singleton."""
    global _global_citation_validator
    if _global_citation_validator is None:
        _global_citation_validator = CitationValidator(min_support_score=min_support_score)
    return _global_citation_validator
